### ISSUE TITLE
Problem running hitch init

### ISSUE THREAD

**Issue by gaqzi** [hitchtest/hitch#2]
Hi,

I'm trying to get Hitch setup on my machine but it's blowing up just as it's finishing the init.

Given the output I thought it might have something to do with `click` versions so I tried downgrading, but stepping down until version 3.3 didn't change anything.

Any suggestions for what to try out? :)

The output given:

``` shell
$ hitch init
[…]
Collecting ipython-genutils (from traitlets->ipython->hitchtest)
  Using cached ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting path.py (from pickleshare->ipython->hitchtest)
  Using cached path.py-7.6-py2.py3-none-any.whl
Installing collected packages: MarkupSafe, jinja2, psutil, pyyaml, colorama, requests, simplegeneric, ipython-genutils, decorator, traitlets, path.py, pickleshare, gnureadline, pexpect, appnope, ipython, patool, click, hitchtest
Successfully installed MarkupSafe-0.23 appnope-0.1.0 click-4.1 colorama-0.3.3 decorator-4.0.2 gnureadline-6.3.3 hitchtest-0.7 ipython-4.0.0 ipython-genutils-0.1.0 jinja2-2.8 path.py-7.6 patool-1.8 pexpect-3.3 pickleshare-0.5 psutil-3.1.1 pyyaml-3.11 requests-2.7.0 simplegeneric-0.8.1 traitlets-4.0.0
Traceback (most recent call last):
  File "/Users/ba/.pyenv/versions/3.4.2/bin/hitch", line 9, in <module>
    load_entry_point('hitch==0.4.7', 'console_scripts', 'hitch')()
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/hitch/commandline.py", line 198, in run
    cli()
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/hitch/commandline.py", line 52, in init
    hitchreqs_handle.write(pip_freeze)
TypeError: must be str, not bytes
$ hitch
Traceback (most recent call last):
  File "/Users/ba/.pyenv/versions/3.4.2/bin/hitch", line 9, in <module>
    load_entry_point('hitch==0.4.7', 'console_scripts', 'hitch')()
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/hitch/commandline.py", line 198, in run
    cli()
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 643, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 560, in make_context
    self.parse_args(ctx, args)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 951, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 416, in get_help
    return self.command.get_help(self)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 772, in get_help
    self.format_help(ctx, formatter)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 787, in format_help
    self.format_options(ctx, formatter)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 892, in format_options
    self.format_commands(ctx, formatter)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 947, in format_commands
    formatter.write_dl(rows)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/formatting.py", line 178, in write_dl
    widths = measure_table(rows)
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/formatting.py", line 11, in measure_table
    widths[idx] = max(widths.get(idx, 0), term_len(col))
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/_compat.py", line 531, in term_len
    return len(strip_ansi(x))
  File "/Users/ba/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/_compat.py", line 468, in strip_ansi
    return _ansi_re.sub('', value)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by crdoconnor** [comment]
Ok that was embarrassing. Apparently I needed to do more extensive testing on the bootstrap script with python 3.

FIxed here : https://github.com/hitchtest/hitch/commit/b5975be40d05a917a1b5d30dcff279ade100a52a

You can pip install -U hitch to get the fix.

**Comment by crdoconnor** [comment]
Thanks for reporting!

**Comment by gaqzi** [comment]
@crdoconnor worked like a charm, thanks! :)

**Comment by Eraldo** [comment]
The mention was not intended.. sorry.
