### ISSUE TITLE
Running in Debian Docker Container

### ISSUE THREAD

**Issue by mjsisley** [hitchtest/hitch#27]
Thank you for all the work on this project. I am trying to run hitch in a python3.5 container. I get the following error on hitch init. I am getting a key error: debian-. 

`hitch_1       | Installing collected packages: unixpackage, click, hitchsystem
hitch_1       | Successfully installed click-6.6 hitchsystem-0.1.4 unixpackage-0.4.2
hitch_1       | Traceback (most recent call last):
hitch_1       |   File "/app/tests/.hitch/virtualenv/bin/hitchsystem", line 11, in <module>
hitch_1       |     sys.exit(commandline.run())
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/hitchsystem/commandline.py", line 94, in run
hitch_1       |     cli()
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
hitch_1       |     return self.main(*args, **kwargs)
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/click/core.py", line 696, in main
hitch_1       |     rv = self.invoke(ctx)
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
hitch_1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
hitch_1       |     return ctx.invoke(self.callback, **ctx.params)
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
hitch_1       |     return callback(*args, **kwargs)
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/hitchsystem/commandline.py", line 65, in installpackages
hitch_1       |     unixpackage.install(_all_required_packages(), polite=True)
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/unixpackage/api.py", line 48, in install
hitch_1       |     install(generic_packages[10:], polite=polite)
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/unixpackage/api.py", line 51, in install
hitch_1       |     package_group = package_group_for_my_distro()(generic_packages)
hitch_1       |   File "/app/tests/.hitch/virtualenv/lib/python3.5/site-packages/unixpackage/package_group.py", line 238, in package_group_for_my_distro
hitch_1       |     this_distro, utils.lsb_release_codename().lower()
hitch_1       | KeyError: 'debian-'
hitch_1       | 
hitch_1       | Error initializing hitch. Problem checklist:
hitch_1       | 
hitch_1       | * Was there a problem with your internet?
hitch_1       | * Was there a python package being installed that couldn't compile?
hitch_1       | 
hitch_1       | 
hitch_1       | Try searching for any errors printed above or raising an issue at:
hitch_1       | http://github.com/hitchtest/hitch/issues/`

**Comment by crdoconnor** [comment]
Hi!

Thanks for trying hitch!

Can you point me to the container you're using to run it in?

**Comment by mjsisley** [comment]
The base image is python:3.5 from dockerhub https://hub.docker.com/_/python/

Dockerfile is as follows:

`FROM python:3.5
ENV PYTHONUNBUFFERED 1

COPY ./requirements /requirements
RUN pip install -r /requirements/test.txt

COPY ./compose/hitch/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app/tests
ENTRYPOINT ["/bin/bash", "-e", "/entrypoint.sh"]`

Relevant part of docker-compose.yml:

`hitch:
  dockerfile: Dockerfile-hitch
  build: .
  volumes_from:
    - django
  links:
- django`

hitch init is called in entrypoint.sh 

Thanks for your help.

**Comment by crdoconnor** [comment]
Thanks. I'll take a look at this a little later on.

**Comment by crdoconnor** [comment]
Hi!

That specific bug is fixed.

It's probably better if you run hitch using a different image than the stock python one however. I'd recommend ubuntu trusty.
